### ISSUE TITLE
Incorrect BootCamp.xml Reference

### ISSUE THREAD

**Issue by HighMacGuy** [fgimian/campies#2]
Line 365 is currently:
'/Volumes/Boot Camp/BootCamp/BootCamp.xml'

Line 365 should be:
'/Volumes/Boot Camp/BootCamp.xml'

**Comment by fgimian** [comment]
This sadly appears to differ based on the Boot Camp package.  In my case it was correctly in a BootCamp sub-directory.

I suggest simply using Boot Camp Assistant to download your drivers and follow my [guide](http://fgimian.github.io/blog/2016/03/12/installing-windows-10-on-a-mac-without-bootcamp/) for installing Windows without Boot Camp afterwards.
